let CreateDateTable = (StartDateCol as list, EndDateCol as list, FiscalMonthNumber as number ) as table =>

 let
// Select The Minimum start Date column and Maximum Start Date Column and Enter the Fiscal year Start Month

    StartDate = #date(Date.Year(List.Min(StartDateCol)),1,1),
    EndDate = #date(Date.Year(List.Max(EndDateCol)),12,31),
    
// Edit FiscalMonthNumber parameter to change the start of Fiscal year 
    StartOfFiscalYear = FiscalMonthNumber,
    NumberOfDays = Duration.Days( EndDate - StartDate ),
    Dates = List.Dates(StartDate, NumberOfDays+1, #duration(1,0,0,0)),
    Creator = "Ramesh Khade(https://www.linkedin.com/in/khaderamesh/)",
    #"Converted to Table" = Table.FromList(Dates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Date"}}),
    #"Changed Type to Date" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}}),
    #"Inserted Year" = Table.AddColumn(#"Changed Type to Date", "Year", each Date.Year([Date]), type number),
    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([Date]), type number),
    #"Inserted Month Name" = Table.AddColumn(#"Inserted Month", "Month Name", each Date.MonthName([Date]), type text),
    #"Inserted First Characters" = Table.AddColumn(#"Inserted Month Name", "First Characters", each Text.Start([Month Name], 3), type text),
    #"Month Name Short" = Table.RenameColumns(#"Inserted First Characters",{{"First Characters", "Month Name Short"}}),
    #"Inserted Quarter" = Table.AddColumn(#"Month Name Short", "Quarter", each Date.QuarterOfYear([Date]), type number),
    #"Inserted Merged Column" = Table.AddColumn(#"Inserted Quarter", "Qtr", each Text.Combine({"Q", Text.From([Quarter], "en-IN")}), type text),
    #"Inserted Week of Year" = Table.AddColumn(#"Inserted Merged Column", "Week of Year", each Date.WeekOfYear([Date]), type number),
    #"Inserted Week of Month" = Table.AddColumn(#"Inserted Week of Year", "Week of Month", each Date.WeekOfMonth([Date]), type number),
    #"Inserted Day" = Table.AddColumn(#"Inserted Week of Month", "Day", each Date.Day([Date]), type number),
    #"Inserted Day of Week" = Table.AddColumn(#"Inserted Day", "Day of Week", each Date.DayOfWeek([Date]), type number),
    #"Inserted Day of Year" = Table.AddColumn(#"Inserted Day of Week", "Day of Year", each Date.DayOfYear([Date]), type number),
    #"Inserted Day Name" = Table.AddColumn(#"Inserted Day of Year", "Day Name", each Date.DayOfWeekName([Date]), type text),
    #"Inserted First Characters1" = Table.AddColumn(#"Inserted Day Name", "First Characters", each Text.Start([Day Name], 3), type text),
    #"Day Name Short" = Table.RenameColumns(#"Inserted First Characters1",{{"First Characters", "Day Name Short"}}),
    #"Added Custom" = Table.AddColumn(#"Day Name Short", "Fiscal Year", each if [Month]>=StartOfFiscalYear
then [Year]+1
else [Year]),
    #"Changed Type of Inserted Coloumns to Whole Number" = Table.TransformColumnTypes(#"Added Custom",{{"Fiscal Year", Int64.Type}, {"Day of Year", Int64.Type}, {"Day of Week", Int64.Type}, {"Day", Int64.Type}, {"Week of Month", Int64.Type}, {"Week of Year", Int64.Type}, {"Quarter", Int64.Type}, {"Month", Int64.Type}, {"Year", Int64.Type}}),
    #"Added Custom1" = Table.AddColumn(#"Changed Type of Inserted Coloumns to Whole Number", "Fiscal Period", each if [Month]>=StartOfFiscalYear
then [Month]-(StartOfFiscalYear-1)
else [Month]+(12-StartOfFiscalYear+1)),
    #"Changed Type Fiscal Period to Whole Number" = Table.TransformColumnTypes(#"Added Custom1",{{"Fiscal Period", Int64.Type}}),
    #"Inserted Division" = Table.AddColumn(#"Changed Type Fiscal Period to Whole Number", "Inserted Division", each [Fiscal Period] / 3, type number),
    #"Rounded Up" = Table.TransformColumns(#"Inserted Division",{{"Inserted Division", Number.RoundUp, Int64.Type}}),
    #"Renamed Rounded Coloumn" = Table.RenameColumns(#"Rounded Up",{{"Inserted Division", "Fiscal Quarter"}}),
    #"Renamed Fiscal Quarter" = Table.RenameColumns(#"Renamed Rounded Coloumn",{{"Fiscal Quarter", "Fiscal Quarter Number"}}),
    #"Added Fiscal Qtr" = Table.AddColumn(#"Renamed Fiscal Quarter", "Merged", each Text.Combine({"Qtr", Text.From([Fiscal Quarter Number], "en-IN")}), type text),
    #"Renamed Fiscal Qtr" = Table.RenameColumns(#"Added Fiscal Qtr",{{"Merged", "Fiscal Quarter"}}),
    #"Inserted Week" = Table.AddColumn(#"Renamed Fiscal Qtr", "Merged", each Text.Combine({"Week", Text.From([Week of Year], "en-IN")}), type text),
    #"Renamed Week" = Table.RenameColumns(#"Inserted Week",{{"Merged", "Week"}}),
    #"Renamed Multiple Columns" = Table.RenameColumns(#"Renamed Week",{{"Day", "Day Number"}, {"Month", "Month Number"}, {"Month Name Short", "Month"}, {"Quarter", "Quarter Number"}, {"Qtr", "Quarter"}, {"Day Name Short", "Day"}}),
    #"Columns Sorted" = Table.SelectColumns(#"Renamed Multiple Columns",{"Date", "Day", "Day Name", "Day Number", "Day of Week", "Day of Year", "Fiscal Period", "Fiscal Quarter", "Fiscal Quarter Number", "Fiscal Year", "Month", "Month Name", "Month Number", "Quarter", "Quarter Number", "Week", "Week of Month", "Week of Year", "Year"}),
    Calender = Table.Sort(#"Columns Sorted",{{"Date", Order.Ascending}})
in
    Calender,

    documentation = [
        Documentation.Name = " Calendar ",                                     
        Documentation.Description = " This custom M function query can be used to create a calendar table with M Query. 
          Required input parameters :
          1. Start Date or Minimum date column from Data for the Calendar Dates
          2. End Date or Maximum date column from Data for the Calendar Dates
          3.  Fiscal Month Start month number for fiscal month date columns",                                
        Documentation.Source = " https://github.com/khaderamesh/Public/blob/main/PowerBI/MQuery/DataClean ",                            
        Documentation.Version = " 1.1 ",                                           
        Documentation.Author = " Ramesh Khade (https://in.linkedin.com/in/khaderamesh) "                                              

    ]

in
    CreateDateTable
